[package]
name = "tryke"
version = "0.1.0"
edition = "2024"
description = "python testing"
license = "MIT"
repository = "https://github.com/thejchap/tryke"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
