[project]
name = "tryke"
version = "0.0.4"
description = "tryke â€” python testing tool"
readme = "README.md"
authors = [{ name = "Justin Chapman", email = "commonmodestudio@gmail.com" }]
requires-python = ">=3.13"
dependencies = []

[tool.ty.src]
exclude = ["python"] # TODO

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "COM812"]

[tool.maturin]
bindings = "bin"
manifest-path = "crates/tryke/Cargo.toml"
python-source = "python"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.uv.build-backend]
module-root = "python/tryke"

[dependency-groups]
dev = ["ruff~=0.15.4", "ty~=0.0.19"]
