[project]
name = "tryke"
version = "0.1.0.dev3"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Justin Chapman", email = "commonmodestudio@gmail.com" }]
requires-python = ">=3.13"
dependencies = []

[tool.maturin]
bindings = "bin"
manifest-path = "crates/tryke/Cargo.toml"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
