[project]
name = "tryke"
version = "0.0.2"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Justin Chapman", email = "commonmodestudio@gmail.com" }]
requires-python = ">=3.13"
dependencies = []

[tool.maturin]
bindings = "bin"
manifest-path = "crates/tryke/Cargo.toml"
python-source = "python"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = ["ruff~=0.15.4", "ty~=0.0.19"]
